# Generated by Django 3.2.6 on 2022-05-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0002_meeting_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='absentees',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
