# Generated by Django 3.2.6 on 2022-05-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0003_meeting_absentees'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereg',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
