# Generated by Django 3.2.6 on 2022-05-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0005_alter_meeting_absentees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='absentees',
            field=models.TextField(null=True),
        ),
    ]
